[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["python -m venv /opt/venv && /opt/venv/bin/pip install --upgrade pip && /opt/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"
